# Generated by Django 6.0.7 on 2026-07-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100)),
                ('FECHAETA', models.CharField(max_length=100)),
                ('CANTIDAD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TOTAL', models.CharField(max_length=50)),
                ('FECHADESPACHO', models.DateField()),
                ('FECHAENTREGA', models.DateField()),
                ('LOTENUM', models.CharField(max_length=50)),
                ('VENCIMIENTO', models.DateField()),
                ('NUMERODESPACHO', models.CharField(max_length=50)),
            ],
        ),
    ]
